### PR TITLE
Add fastlane plugin

### PR DESCRIPTION
**Pull request by Ruenzuo**
Hey @plu 👋, you're probably familiar with [fastlane](https://fastlane.tools). I like simctl a lot and I felt that there's a `xcrun simctl` interfacing action missing in fastlane, so this PR implements a basic fastlane plugin that uses simctl to run a block within the context of a running and ready simulator.

Notes for the review:

* Tests are missing, I wanted to get feedback from you first about the idea.
* Most of the dotfiles and project structure are generated by fastlane itself with `fastlane new_plugin` command.

### CODE REVIEW

**Comment by plu** [comment]
I love the idea, thanks for implementing that - I bet other users will find that useful too 👍 .

My only concern is that I might not find as much time as I'd like to for maintaining this. So I'm wondering if you'd rather want to have this plugin in a separate repository instead, or if you want to be added to this repository so you can easier maintain it by directly committing to it?

**Comment by Ruenzuo** [comment]
Keeping both gems in the same repo makes a lot of sense to me, and I'd love to help maintaining this project too as I use this gem a lot.

**Comment by plu** [comment]
I've added you on GitHub. Trying to figure out how to do that on RubyGems.

**Comment by plu** [comment]
What email address are you using on RubyGems?

**Comment by Ruenzuo** [comment]
Sent you a DM over there.

**Comment by plu** [comment]
Done. Happy coding & releasing :).

**Comment by plu** [comment]
Awesome! Thank you for all the effort you're putting into this! :)

**Comment by plu** [comment]
🎉

**Pull request merged**
