### PR TITLE
Headless simulators

### PR DESCRIPTION
**Pull request by adamprice**
Added ability to launch and kill a headless simulator.

### CODE REVIEW

**Comment by adamprice** [comment]
Any ideas why that test might have failed against only one of the Xcode 7 builds? I don't have an Xcode 7 install to test against unfortunately. It runs and passes consistently for me on my machine with Xcode 8.

**Comment by plu** [comment]
Thank you for your pull request.

Isn't this doing the same?

https://github.com/plu/simctl/blob/master/lib/simctl/command/boot.rb

There is a `boot` method also available on a device instance. And there's a `shutdown` method.

**Comment by adamprice** [comment]
Haha, you're right. Totally missed that! 😄

**Comment by plu** [comment]
Nevertheless, thank you for your time and effort you put into writing the code and tests, it looked great! If the functionality wasn't there already I'd have merged it.

**Pull request closed without merging**
